### ISSUE TITLE
推理報錯

### ISSUE THREAD

**Issue by DecorousGoat914** [PlayVoice/so-vits-svc-5.0#103]
這個報錯哪個問題?顯卡式cuda是12.2.128的rtx3060laptop版
python svc_inference.py --config configs/base.yaml --model sovits5.0.pth --spk ./data_svc/singer/Matikanetannhauser.npy --wave test.wav --shift 0
Auto run : python whisper/inference.py -w test.wav -p svc_tmp.ppg.npy
test.wav
svc_tmp.ppg.npy
Auto run : python hubert/inference.py -w test.wav -v svc_tmp.vec.npy
test.wav
svc_tmp.vec.npy
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Auto run : python pitch/inference.py -w test.wav -p svc_tmp.pit.csv
test.wav
svc_tmp.pit.csv
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "C:\Users\User\Desktop\so-vits-rtvc\so-vits-svc-5.0-bigvgan-mix-v2\svc_inference.py", line 170, in <module>
    main(args)
  File "C:\Users\User\Desktop\so-vits-rtvc\so-vits-svc-5.0-bigvgan-mix-v2\svc_inference.py", line 112, in main
    load_svc_model(args.model, model)
  File "C:\Users\User\Desktop\so-vits-rtvc\so-vits-svc-5.0-bigvgan-mix-v2\svc_inference.py", line 14, in load_svc_model
    assert os.path.isfile(checkpoint_path)
AssertionError

**Comment by MaxMax2016** [comment]
--model sovits5.0.pth
assert os.path.isfile(checkpoint_path)
AssertionError
文件不存在
