### ISSUE TITLE
inference result is too noisy

### ISSUE THREAD

**Issue by meriamOu** [PlayVoice/so-vits-svc-5.0#109]
hey, 
I run the repo with the suggested audio,  

python svc_inference.py --config configs/base.yaml --model ./vits_pretrain/sovits5.0.pretrain.pth --spk ./configs/singers/singer0001.npy --wave test.wav
 
The inference result is very noisy. I can not hear the lyrics at all.
Any suggestions in this case?
Thank you

**Comment by MaxMax2016** [comment]
you can compare with hugging face demo.
