### ISSUE TITLE
wtf man

### ISSUE THREAD

**Issue by ghostly4004** [PlayVoice/so-vits-svc-5.0#11]
from whisper.model import Whisper, ModelDimensions
ModuleNotFoundError: No module named 'whisper'

**Comment by ghostly4004** [comment]
> from whisper.model import Whisper, ModelDimensions ModuleNotFoundError: No module named 'whisper'

from vits import spectrogram
ModuleNotFoundError: No module named 'vits'

xd

**Comment by MaxMax2016** [comment]
export PYTHONPATH=$PWD

**Comment by ghostly4004** [comment]
> export PYTHONPATH=$PWD

**Comment by ghostly4004** [comment]
> export PYTHONPATH=$PWD

FileNotFoundError: [Errno 2] No such file or directory: '/speaker_pretrain/best_model.pth.tar'
FileNotFoundError: [Errno 2] No such file or directory: 'whisper_pretrain\\medium.pt'

**Comment by ghostly4004** [comment]
omg, why are there so many problems with 5.0.....

**Comment by ghostly4004** [comment]
@MaxMax2016 thx!

**Comment by Parisa-Bagherzadeh** [comment]
> > export PYTHONPATH=$PWD
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/speaker_pretrain/best_model.pth.tar' FileNotFoundError: [Errno 2] No such file or directory: 'whisper_pretrain\medium.pt' FileNotFoundError: [Errno 2] No such file or directory: 'svc_out.wav'

In Install dependencies section of the readme you can find the links of best_model.pth.tar and medium.pt to download them
