### ISSUE TITLE
about sovits5.0.pretrain.pth

### ISSUE THREAD

**Issue by aTeNaNt** [PlayVoice/so-vits-svc-5.0#112]
Hello! 
I'm a user(and BEGINNER) who enjoying so-vits-svc-5.0!
I have to select right song that I put into it. but I don't know about which language is the best thing in this model.
so  If it's not too mush trouble, Could you explain me what sovits5.0.pretrain.pth was generated from?
(like which languages, how many people's voice in there) 
and what model was used to generate sovits5.0.pretrain.pth?
Thank you!

**Comment by MaxMax2016** [comment]
vctk-english & opensinger-chinese

**Comment by aTeNaNt** [comment]
really appriciate your quick answer :)
I hate to ask, but I have one more.
I'm gonna study way of generally making pretrain.pth.
If you don't mind,  Could you explain me how you did train and generate sovits5.0.pretrain.pth with vctk-english & opensinger-chinese?
really thank you!

**Comment by MaxMax2016** [comment]
the same way as in readme. but without out pretrain.pth, you should have a bigger learning_rate: 2e-4

**Comment by aTeNaNt** [comment]
I'm so Sorry to bother you, I can't see how you made sovits.5.0.pretrain.pth. I can see "Download Download pretrain model sovits5.0.pretrain.pth" ,already made, in README. (maybe I couldn't read README properly because I'm super beginner.)
What I'm trying to find out are, which model was used to make  sovits5.0.pretrain.pth and if you made sovits5.0.pretrain.pth using vctk-english & opensinger-chinese only. (because the last time I saw README, there is a lot of data used to make sovits5.0.pretrain.pth  more than you told me.)
so If It's not too much trouble, Could you explain me about these things?
Thank you.
(once again I'm so Sorry to bug you.)

**Comment by MaxMax2016** [comment]
you can see the code in svc_export.py
```
def main(args):
    hp = OmegaConf.load(args.config)
    model = SynthesizerInfer(
        hp.data.filter_length // 2 + 1,
        hp.data.segment_size // hp.data.hop_length,
        hp)

    # save_pretrain(args.checkpoint_path, "sovits5.0.pretrain.pth")
    load_model(args.checkpoint_path, model)
    save_model(model, "sovits5.0.pth")
```
when you use so may data contains so may pepole, the trained model can be used as sovits5.0.pretrain.pth. It is just a name, no different.

**Comment by aTeNaNt** [comment]
Really thank you! Thanks to your comment I can keep enjoying!
