### ISSUE TITLE
which model did you make sovits5.0.pretrain.pth using?

### ISSUE THREAD

**Issue by AllInGood** [PlayVoice/so-vits-svc-5.0#113]
when I used this code, I also used  [sovits5.0.pretrain.pth](https://github.com/PlayVoice/so-vits-svc-5.0/releases/download/5.0/sovits5.0.pretrain.pth).
I have to research about this sovits5.0.pretrain.pth. (for presentation)
but I can't find them out on my own.
Which model did you make this [pretrain model file](https://github.com/PlayVoice/so-vits-svc-5.0/releases/download/5.0/sovits5.0.pretrain.pth) using? And,
you mentioned that you used opensinger-chinese as a pretrain.pth dataset in other issue,
the opensinger-chinese is opencpop(in Dataset README)? 
thank you.

**Comment by MaxMax2016** [comment]
https://github.com/Multi-Singer/Multi-Singer.github.io

You  can find Google Drive share for : OpenSinger.tar.gz
