### ISSUE TITLE
demo中奇怪的模糊

### ISSUE THREAD

**Issue by YacratesWyh** [PlayVoice/so-vits-svc-5.0#114]
我使用huggingface中的demo,音色测试丁真的短音频效果很不好，几乎不能分辨声音，是哪里有问题吗。
plus我使用的音频
[DM_20230908175340_003.zip](https://github.com/PlayVoice/so-vits-svc-5.0/files/12558158/DM_20230908175340_003.zip)

**Comment by MaxMax2016** [comment]
whisper需要使用30秒左右的音频，这个测试音频太短了。另外SVC是用于转换歌声的。

https://github.com/PlayVoice/so-vits-svc-5.0/assets/16432329/995d5515-978b-431a-9f42-38cc2af8a534

https://github.com/PlayVoice/so-vits-svc-5.0/assets/16432329/ccb23436-7f40-42e4-b33d-7462a93760ca
