### ISSUE TITLE
感觉我这儿出了点问题

### ISSUE THREAD

**Issue by uuusername** [PlayVoice/so-vits-svc-5.0#117]
大佬好，我的训练数据有260MB，时长为25分钟；配置是4060+13代i5，目前已经训练了四十个小时，最新的两串是”2023-09-17 01:12:07,173 - INFO - Saved checkpoint to: chkpt\sovits5.0\sovits5.0_1945.pt“和“2023-09-17 01:13:00,976 - INFO - epoch 1946 | g 11.2408 m 0.4326 s 7.8074 d 0.3701 k 0.1750 r 0.2682 i 0.4254 | step 40900”，同时我去查看文件时发现chkpt文件夹已经达到了230GB，总感觉有点不对劲......是哪里出了问题吗？

**Comment by uuusername** [comment]
训练数据有178个音频文件，短的3秒，长的20秒

**Comment by MaxMax2016** [comment]
没看到有什么问题啊

**Comment by uuusername** [comment]
> 没看到有什么问题啊

好的，没问题就行，因为我觉得chkpt文件夹达到了230GB，这个大小有点恐怖......

**Comment by MaxMax2016** [comment]
设置里面可以设置保存间隔，现在你可以手动删除一些

**Comment by uuusername** [comment]
> 设置里面可以设置保存间隔，现在你可以手动删除一些

好的，明白了
顺便一提现在已经到了“2023-09-17 18:38:22,699 - INFO - epoch 2355 | g 12.2376 m 0.4731 s 8.9033 d 0.3744 k 0.2182 r 0.2193 i 0.3123 | step 49500”了，那大概还有多久才训练完？有一种，仿佛永远训练不完了的感觉......已经跑了四十五个小时了

**Comment by MaxMax2016** [comment]
不会自动停，看loss应该可以了

**Comment by uuusername** [comment]
> 不会自动停，看loss应该可以了

噢，这个loss是指哪个？意思是说我现在这个模型训练够了是嘛？（实在不好意思我是纯小白，从来没摸过这些，完全是照着教程一步步过来的，问题可能比较傻请见谅......）

**Comment by uuusername** [comment]
> 不会自动停，看loss应该可以了

再问一句，我运行了

> 不会自动停，看loss应该可以了

再请教请教，我运行了推理之后蹦出来这个：

Traceback (most recent call last):
  File "E:\AIsinging\so-vits-svc-5.0-bigvgan-mix-v2\svc_export.py", line 68, in <module>
    main(args)
  File "E:\AIsinging\so-vits-svc-5.0-bigvgan-mix-v2\svc_export.py", line 56, in main
    load_model(args.checkpoint_path, model)
  File "E:\AIsinging\so-vits-svc-5.0-bigvgan-mix-v2\svc_export.py", line 11, in load_model
    assert os.path.isfile(checkpoint_path)
AssertionError

这个怎么解决？谢谢大佬

**Comment by MaxMax2016** [comment]
够了，m平均0.45以下就差不多了

**Comment by uuusername** [comment]
> 够了，m平均0.45以下就差不多了

再请教请教，我运行了推理之后蹦出来这个：

Traceback (most recent call last):
File "E:\AIsinging\so-vits-svc-5.0-bigvgan-mix-v2\svc_export.py", line 68, in
main(args)
File "E:\AIsinging\so-vits-svc-5.0-bigvgan-mix-v2\svc_export.py", line 56, in main
load_model(args.checkpoint_path, model)
File "E:\AIsinging\so-vits-svc-5.0-bigvgan-mix-v2\svc_export.py", line 11, in load_model
assert os.path.isfile(checkpoint_path)
AssertionError

这个怎么解决？去网上搜过了，没看懂......麻烦了，谢谢大佬！

**Comment by MaxMax2016** [comment]
python svc_export.py --config configs/base.yaml --checkpoint_path chkpt/sovits5.0/***.pt

/***.pt要选你训练出来的模型

**Comment by uuusername** [comment]
> python svc_export.py --config configs/base.yaml --checkpoint_path chkpt/sovits5.0/***.pt
> 
> /***.pt要选你训练出来的模型

明白了，应该是改成“sovits5.0/sovits5.0_2455.pt"，我改成了“sovits5.0/2455.pt"，果然是个很傻的问题......谢谢大佬！

**Comment by uuusername** [comment]
> python svc_export.py --config configs/base.yaml --checkpoint_path chkpt/sovits5.0/***.pt
> 
> /***.pt要选你训练出来的模型

谢谢大佬，完全理解了
