### ISSUE TITLE
使用svc_inference_post进行后置处理的时候发现损失很大

### ISSUE THREAD

**Issue by synuwxy** [PlayVoice/so-vits-svc-5.0#118]
我在尝试使用svc_inference_post进行去噪后处理，推理出来的结果发现音频损失非常大，很多完整句子中的部分音频一并被去除了，看起来像是某个阈值设置的问题，请问一下有那些参数可以调整这个阈值么？

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/so-vits-svc-5.0/blob/bigvgan-mix-v2/svc_inference_post.py#L37
调节参数threshold=0.2

**Comment by synuwxy** [comment]
好的，感谢~
