### ISSUE TITLE
When converting Chinese speech instead of singing voices, there are some issues with the tone 

### ISSUE THREAD

**Issue by 450586509** [PlayVoice/so-vits-svc-5.0#119]
When I use it to convert Chinese speech , the pronunciation tones sometimes go wrong, a bit like foreigners who haven't mastered the tones speaking Chinese.

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/whisper-vits-svc/issues/95

使用RMVPE提取pitch

**Comment by roman-online** [comment]
> #95
> 
> Используйте RMVPE для извлечения смол

Do you mean use RVC with RMVPE? Or can RMVPE be used with whisper-vits-svc ?

> #95
> 
> 使用RMVPE提取pitch

Do you mean use RVC with RMVPE? Or can RMVPE be used with whisper-vits-svc ? If yes, then please tell me how this can be done

**Comment by MaxMax2016** [comment]
@roman-online https://github.com/thestmitsuki/so-vits-svc-rmvpe
https://github.com/DLSeed/so-vits-svc-5.0
