### ISSUE TITLE
Any reason why whisper is used instead of HuBERT/contentvec

### ISSUE THREAD

**Issue by Kickbub** [PlayVoice/so-vits-svc-5.0#12]
Just curious

**Comment by MaxMax2016** [comment]
for noise robust

**Comment by Kickbub** [comment]
Also, how do I select speaker when inferencing on my own model? Is there a .npy file saved somewhere?

**Comment by MaxMax2016** [comment]
YES, python prepare/preprocess_speaker.py data_svc/waves-16k/ data_svc/speaker

**Comment by Kickbub** [comment]
Do they all sound the same? There is 1 `.spk.npy` for every wav.
