### ISSUE TITLE
电音比较浓厚

### ISSUE THREAD

**Issue by luyao-cv** [PlayVoice/so-vits-svc-5.0#125]
、训练数据：歌唱半小时
训练epoch:3000

不知道是不是数据没处理干净的原因，有什么缓解的办法吗

**Comment by MaxMax2016** [comment]
方不方便提供训练数据给我训练一下呢？训练数据混响音效可能会导致电音

**Comment by luyao-cv** [comment]
可以的
链接: https://pan.baidu.com/s/1iFTxCMKA-rtmDmouFtsh0A?pwd=5667 提取码: 5667 

感谢

**Comment by MaxMax2016** [comment]
收到，我先研究下

**Comment by MaxMax2016** [comment]
这是用您提供的数据训练的模型效果（没有电音呀）

训练步骤：
1，把您提供的音频，全都用UVR5做了一遍去混响
2，去掉了质量一听就很差的音频
3，去掉了有合唱的部分
4，音频切分
5，训练

如果您需要这个模型，我可以发送您

**Comment by luyao-cv** [comment]
你好，可以把模型还有数据分享给我吗～感谢，请问训了多少epoch和iteration呀～

**Comment by luyao-cv** [comment]
UVR5去混响真的太重要了！！！我用的mac  m2芯的，去混响每次都会自动退出，所以做的不好

**Comment by MaxMax2016** [comment]
链接：https://pan.baidu.com/s/1Fws3VzWXEJcZf2NW6towfw?pwd=dcrs 
提取码：dcrs

数据&模型&日志

**Comment by luyao-cv** [comment]
感谢～

**Comment by MaxMax2016** [comment]
下载完后告诉我一下，我好删除下载链接

**Comment by luyao-cv** [comment]
下好啦～谢谢小姐姐

**Comment by ShadowLoveElysia** [comment]
> 下好啦～谢谢小姐姐
虽然但是，ta是男的

**Comment by luyao-cv** [comment]
> 这是用您提供的数据训练的模型效果（没有电音呀）
> 
>  luyao_faruxue.mov 
> 训练步骤： 1，把您提供的音频，全都用UVR5做了一遍去混响 ![luyao_uvr5](https://user-images.githubusercontent.com/16432329/274494999-1f89668c-c1e9-4e23-b8aa-4ffe817858fa.jpg) 2，去掉了质量一听就很差的音频 3，去掉了有合唱的部分 4，音频切分 5，训练
> 
> 如果您需要这个模型，我可以发送您

你好，请问这个推理的音频能发我么，另外是否有做声调处理呢，我推理出来的结果是这样的。
链接: https://pan.baidu.com/s/1Z3q9BzfTxjuuisrVR3GoVg?pwd=4ekv 提取码: 4ekv 
另外这个可以删掉么～感谢

**Comment by MaxMax2016** [comment]
我的推理源

https://github.com/PlayVoice/whisper-vits-svc/assets/16432329/35db194f-feda-4bac-a409-6759addeab3a

把后缀改成wav

**Comment by luyao-cv** [comment]
谢谢～

**Comment by panxin801** [comment]
> 这是用您提供的数据训练的模型效果（没有电音呀）
> 
> 训练步骤： 1，把您提供的音频，全都用UVR5做了一遍去混响 2，去掉了质量一听就很差的音频 3，去掉了有合唱的部分 4，音频切分 5，训练
> 
> 如果您需要这个模型，我可以发送您

 请问您uvr5去混响用的那个模型呢？
