### ISSUE TITLE
svc_export.py error

### ISSUE THREAD

**Issue by bukhalmae145** [PlayVoice/so-vits-svc-5.0#128]
python svc_export.py --config "configs/base.yaml" --checkpoint_path "chkpt/김 동률/***.pt"

/Users/workstation/Music/whisper-vits-svc/whisper-vits-svc/lib/python3.8/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "svc_export.py", line 68, in <module>
    main(args)
  File "svc_export.py", line 56, in main
    load_model(args.checkpoint_path, model)
  File "svc_export.py", line 11, in load_model
    assert os.path.isfile(checkpoint_path)
AssertionError

**Comment by MaxMax2016** [comment]
***.pt should be a real model path, like **chkpt/sovits5.0/sovits5.0_0500.pt**

**Comment by bukhalmae145** [comment]
but i have multiple models such as sovits5.0_0025.pt, sovits5.0_0050.pt, sovits5.0_0075.pt

**Comment by MaxMax2016** [comment]
choose big number

**Comment by bukhalmae145** [comment]
thank you
