### ISSUE TITLE
pipeline

### ISSUE THREAD

**Issue by luyao-cv** [PlayVoice/so-vits-svc-5.0#131]
整个流程的pipeline可以提供或者描述下吗？

**Comment by luyao-cv** [comment]
> 整个流程的pipeline可以提供或者描述下吗？

跟V4比有哪些区别呢？V4也有whisper-ppg 作为编码提取特征

**Comment by MaxMax2016** [comment]
本项目特性见readme

**Comment by luyao-cv** [comment]
请问这么理解对吗？
1.  使用TacotronSTFT 提取mel（梅尔）频谱信号值x;
2. 训楼编码器，使用混合的（whisper ppg + hubert ssl）语音编码器对x进行编码x';
3. 训练crepe，提取音高；
4. 训练解码器，使用解码器bigvgan将mel x‘ 转化为音频wav的输出y;
loss包含：
spk_loss: 分类器损失
mel_loss：生成的频谱图和提取的GT频谱图的损失
sc_loss, mag_loss：这俩个也是频谱损失，和上面有什么区别吗
score_loss：生成器损失？
feat_loss：生成器和判别器的损失
loss_kl: 这个是计算什么的呢？
