### ISSUE TITLE
Question about pitch(f0) hop_length

### ISSUE THREAD

**Issue by Gabibing** [PlayVoice/so-vits-svc-5.0#154]
First, I would like to express my gratitude to everyone who has contributed to maintaining such a wonderful repository.

While reviewing the code, I noticed that two files require different hop_length values.
in prepare/preprocess_crepe.py, it is set to 160,
but in vits/data_utils.py, it is set to 320.
Is this a bug, or is there a process in place to reconcile these differences?

**Comment by MaxMax2016** [comment]
prepare/preprocess_crepe.py use 16kHz wave
vits/data_utils.py, use 32kHz wave

**Comment by Gabibing** [comment]
I see. Thank you for the answer.
