### ISSUE TITLE
音色还原，但是读音偶尔不标准，请问是什么原因

### ISSUE THREAD

**Issue by codexq123** [PlayVoice/so-vits-svc-5.0#157]
例如“鸡你太美（mei3）”，输出音频是“鸡你太美（mei2）”，请问是数据集的问题吗，还是其他原因，如何解决？

数据集：动漫数据26min，demucs去除杂音，再人肉听筛选走杂音太大的。

训练：利用预训练模型，finetune大概4万step

**Comment by MaxMax2016** [comment]
可能是pitch提取的问题，您可以尝试RMVPE:
https://github.com/thestmitsuki/so-vits-svc-rmvpe
https://github.com/DLSeed/so-vits-svc-5.0

**Comment by codexq123** [comment]
> 可能是pitch提取的问题，您可以尝试RMVPE: https://github.com/thestmitsuki/so-vits-svc-rmvpe https://github.com/DLSeed/so-vits-svc-5.0

感谢及时回复，我尝试上面这个项目重新训练一下

**Comment by codexq123** [comment]
> > 可能是pitch提取的问题，您可以尝试RMVPE: https://github.com/thestmitsuki/so-vits-svc-rmvpe https://github.com/DLSeed/so-vits-svc-5.0
> 
> 感谢及时回复，我尝试上面这个项目重新训练一下

无须重新训练，将RMVPE作为pitch预测，推理再无音调问题，问题解决
