### ISSUE TITLE
Reproduction of sovits5.0.pretrain.pth

### ISSUE THREAD

**Issue by leonardoboulitreau** [PlayVoice/so-vits-svc-5.0#158]
Hello, first of all, thank you for all the excelent work!

I am trying to replicate the avaliable pretrained model. If possible, I would like to know the data you used to train, and if any param was set differently from the ones in the default base.yaml config.

**Comment by MaxMax2016** [comment]
data:
Multi-Singer, https://github.com/Multi-Singer/Multi-Singer.github.io
VCTK, https://datashare.ed.ac.uk/handle/10283/2651

config:
learning_rate: 2e-4

**Comment by panxin801** [comment]
Hello, Thank you for your wonderful work, but I want to ask how much epoch do you trained, and what's the batchsize and accum_step, and the last one question is what gpu do you used for train, like A800 or A100 ? Thanks for your reply
