### ISSUE TITLE
现在需要男歌手翻唱女声的歌曲，使用的是singer0008，因为软件没有变调功能，出来的效果不太行

### ISSUE THREAD

**Issue by ILG2021** [PlayVoice/so-vits-svc-5.0#178]
不知道这种情况如何处理，rvc可以自己调音高。

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/so-vits-svc-5.0/blob/bigvgan-mix-v2/svc_inference.py#L197~L199

**Comment by ILG2021** [comment]
> https://github.com/PlayVoice/so-vits-svc-5.0/blob/bigvgan-mix-v2/svc_inference.py#L197~L199

非常感谢。
