### ISSUE TITLE
关于版权方面

### ISSUE THREAD

**Issue by ILG2021** [PlayVoice/so-vits-svc-5.0#186]
如果基于底模训练自己的歌手（声音已授权）产出的作品是否存在版权方面的问题，需要署名或者其他什么要求吗？

**Comment by ShadowLoveElysia** [comment]
未授权建议标，已授权可以问问本人能不能用于训练

**Comment by ILG2021** [comment]
> 未授权建议标，已授权可以问问本人能不能用于训练

多谢回复，歌手这边没有什么问题。主要是想确认下底模方面的
