### ISSUE TITLE
Missing data perturbation code in Data preprocessing. 

### ISSUE THREAD

**Issue by MuruganR96** [PlayVoice/so-vits-svc-5.0#188]
I couldn't find Data perturbation code in Data preprocessing.  

@MaxMax2016  could you add the data perturbation script? please help me

Thanks

**Comment by MaxMax2016** [comment]
Here:
https://github.com/PlayVoice/so-vits-svc-5.0/blob/bigvgan-mix-v2/vits/models.py#L183~L185

```
def forward(self, ppg, vec, pit, spec, spk, ppg_l, spec_l):
        ppg = ppg + torch.randn_like(ppg) * 1  # Perturbation
        vec = vec + torch.randn_like(vec) * 2  # Perturbation
```
