### ISSUE TITLE
断音明显，或许是切片问题？

### ISSUE THREAD

**Issue by KakaruHayate** [PlayVoice/so-vits-svc-5.0#25]
[svc_out(20).zip](https://github.com/PlayVoice/so-vits-svc-5.0/files/11459456/svc_out.20.zip)
如题，可能需要一个交叉淡化？

https://github.com/svc-develop-team/so-vits-svc/blob/4.0/inference_main.py

**Comment by MaxMax2016** [comment]
目前推理使用25S进行切片，在25秒处是切片引起的，这个音频其他位置断音严重，您用的什么提取的F0呢？

**Comment by KakaruHayate** [comment]
> 目前推理使用25S进行切片，在25秒处是切片引起的，这个音频其他位置断音严重，您用的什么提取的F0呢？


默认的crepe

**Comment by MaxMax2016** [comment]
是这个数据集么？https://github.com/KakaruHayate/CODEY_Dataset

**Comment by KakaruHayate** [comment]
> 是这个数据集么？https://github.com/KakaruHayate/CODEY_Dataset

不是，用的Opencpop、kiritan（东北切蒲英）和nus48，为了覆盖音素

**Comment by MaxMax2016** [comment]
从头开始训练的么，训练了多久了呢？

**Comment by KakaruHayate** [comment]
> 从头开始训练的么，训练了多久了呢？

训练了250k（410epoch），数据量应该没你用的opensinger大，差不多收敛了

**Comment by MaxMax2016** [comment]
TensorBoard里面训练过程中的音频正不正常呢？

**Comment by KakaruHayate** [comment]
> TensorBoard里面训练过程中的音频正不正常呢？

用的抢占实例，log没保留，但最后的试听是没问题的（较早的时候也有断音，训练到了无断音的程度）

**Comment by MaxMax2016** [comment]
我也没什么头绪，可能等我stage2训练完，用微调的方式训练吧

**Comment by KakaruHayate** [comment]
> 我也没什么头绪，可能等我stage2训练完，用微调的方式训练吧

你在训练的早期试听有断音吗？

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/so-vits-svc-5.0/releases/tag/v5.2 训练早期音频在log里面，用tensorboard查看

**Comment by KakaruHayate** [comment]
> https://github.com/PlayVoice/so-vits-svc-5.0/releases/tag/v5.2 训练早期音频在log里面，用tensorboard查看

也有，但是比我那边情况好很多，我大概4800条的数据，你那边多少？

**Comment by KakaruHayate** [comment]
https://drive.google.com/file/d/1JklDOhFyZQu2vh8b1UUtcXTBg0Pxir40/view?usp=share_link

推理这首的时候换气声的特征提取似乎有问题

**Comment by yongzhuo** [comment]
After using your Genshin Impact voice training for 2500 steps, I feel that there will be a hoarse voice behind.
