### ISSUE TITLE
how to make pretrain model?

### ISSUE THREAD

**Issue by weituotian** [PlayVoice/so-vits-svc-5.0#3]
`vits_pretrain.pt`

is pretrain model only have one speaker or have mutil speaker?  will us train our dataset on the pretrained first speaker?
why pretrain model is smaller than our trained model, is there a way to convert our model to pretain model?

**Comment by MaxMax2016** [comment]
The code is constantly updated, and you need to use the code package from release page.
svc_export.py is for export clean&small model

**Comment by weituotian** [comment]
好~(￣▽￣)~*
