### ISSUE TITLE
预览模型无变声效果

### ISSUE THREAD

**Issue by stwrd** [PlayVoice/so-vits-svc-5.0#30]
你好，我在本地使用预览模型进行测试时发现没有变声效果，但在hugging face上用同样的音频测试，效果却不一样，请问下我是哪个过程错了呢？
我是按照下面的步骤进行的：
1. 下载预览模型https://github.com/PlayVoice/so-vits-svc-5.0/releases/download/v5.2/sovits5.0.pretrain.pth
2. 使用svc_export.py将sovits5.0.pretrain.pth转成sovits5.0.pth
3. 按照readme的说明进行测试
```
python svc_inference.py --config configs/base.yaml --model sovits5.0.pth --spk ./configs/singers/singer0051.npy --wave test.wav --ppg test.ppg.npy --pit test.csv
```

**Comment by MaxMax2016** [comment]
hugging face上面的模型高频是模糊的，但是无音色泄漏；预览模型有音色泄漏，还在调试；
