### ISSUE TITLE
数据集命名

### ISSUE THREAD

**Issue by Pentalimbed** [PlayVoice/so-vits-svc-5.0#33]
README曰：
> 然后以下面文件结构将数据集放入dataset_raw目录
> ```
> dataset_raw
> ├───speaker0
> │   ├───xxx1-xxx1.wav
> │   ├───...
> │   └───Lxx-0xx8.wav
> └───speaker1
>     ├───xx2-0xxx2.wav
>     ├───...
>     └───xxx7-xxx007.wav
> ```
想问一下这里必须要使用`speaker0`、`speaker1`的命名方式吗？以及下面诸如`Lxx-0xx8`等名称中是否要严格包含这些数字（以及大写L）？

**Comment by MaxMax2016** [comment]
没有命名的要求，只需要满足这样的目录结构

**Comment by Pentalimbed** [comment]
感谢回复，那么这里如果我用了别的speaker名称，之后infer的时候--spk参数使用的npy文件是用哪一个呢？

**Comment by MaxMax2016** [comment]
刚添加了说明

> 6， 提取音色编码均值，用于推理；也可以在生成训练索引中，替换单个音频音色，作为发音人统一音色用于训练
> 
> python prepare/preprocess_speaker_ave.py data_svc/speaker/ data_svc/singer
