### ISSUE TITLE
No module named 'whisper‘.but it seems whisper is built-in

### ISSUE THREAD

**Issue by a-cold-bird** [PlayVoice/so-vits-svc-5.0#38]
(venv) PS D:\so-vits-svc-5.0> python prepare/preprocess_ppg.py -w data_svc/waves-16k/ -p data_svc/whisper
Traceback (most recent call last):
  File "D:\so-vits-svc-5.0\prepare\preprocess_ppg.py", line 6, in <module>
    from whisper.model import Whisper, ModelDimensions
ModuleNotFoundError: No module named 'whisper

i just clone this project,and install dependence,then i run those commands below

python prepare/preprocess_a.py -w ./dataset_raw -o ./data_svc/waves-16k -s 16000
python prepare/preprocess_f0.py -w data_svc/waves-16k/ -p data_svc/pitch
when i run  "python prepare/preprocess_ppg.py -w data_svc/waves-16k/ -p"

occur hapend,

windows 10
Python 3.10.7

help :(

**Comment by a-cold-bird** [comment]
i found i didnt set pythonpath，but when i mv whisper to venv,i solved this problem XXD

**Comment by Parisa-Bagherzadeh** [comment]
> (venv) PS D:\so-vits-svc-5.0> python prepare/preprocess_ppg.py -w data_svc/waves-16k/ -p data_svc/whisper Traceback (most recent call last): File "D:\so-vits-svc-5.0\prepare\preprocess_ppg.py", line 6, in from whisper.model import Whisper, ModelDimensions ModuleNotFoundError: No module named 'whisper
> 
> i just clone this project,and install dependence,then i run those commands below
> 
> python prepare/preprocess_a.py -w ./dataset_raw -o ./data_svc/waves-16k -s 16000 python prepare/preprocess_f0.py -w data_svc/waves-16k/ -p data_svc/pitch when i run "python prepare/preprocess_ppg.py -w data_svc/waves-16k/ -p"
> 
> occur hapend,
> 
> windows 10 Python 3.10.7
> 
> help :(

Hi, to import the module inside the folder whisper , you can use this code 
Whisper = importlib.util.spec_from_file_location("Whisper","whisper/model.py")
