### ISSUE TITLE
issue with zip archive

### ISSUE THREAD

**Issue by Parisa-Bagherzadeh** [PlayVoice/so-vits-svc-5.0#44]
how can i solve this at step4 of Data preprocessing ?
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by MaxMax2016** [comment]
is there more detial log info?

**Comment by Parisa-Bagherzadeh** [comment]
> is there more detial log info?

this is the error i get after i run this : python prepare/preprocess_ppg.py -w data_svc/waves-16k/ -p data_svc/whisper

  File "prepare/preprocess_ppg.py", line 56, in <module>
    whisper = load_model(os.path.join("whisper_pretrain", "medium.pt"))
  File "prepare/preprocess_ppg.py", line 24, in load_model
    checkpoint = torch.load(path, map_location=device)
  File "/home/parisa/anaconda3/envs/voice/lib/python3.7/site-packages/torch/serialization.py", line 778, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/parisa/anaconda3/envs/voice/lib/python3.7/site-packages/torch/serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by MaxMax2016** [comment]
maybe medium.pt is not downloaded completely? you can check whether it's the right size.
