### ISSUE TITLE
Nvidia CUDA 10.1 user here! Can I run this program with pytorch 1.8.1? What is the minimum version requirement?

### ISSUE THREAD

**Issue by TechVillain** [PlayVoice/so-vits-svc-5.0#5]
I am a music instructor and I would love to introduce this lovely AI software to our students to try out.

Here in my school we have several Windows 7 Pro 64-bit computers in our classrooms, running on Nvidia GeForce GTX 660M GPU. According to Nvidia, the highest version of graphic driver we can install is 425.31, and the highest CUDA Toolkit we can install would be 10.1.

According to pytorch dot org, with CUDA version 10.1, the highest torch we can install would be: 
_“torch-1.8.1+cu101-cp39-cp39-win_amd64.whl”._

Here, “cu101” in the file name, is referring to CUDA 10.1. 

Any torch version higher than 1.8.1, will have a higher “cu” number attached in the whl file name, such as: 
_“torch-1.10.0+cu102-cp36-cp36m-win_amd64.whl”_, or
_“torch-1.13.0+cu116-cp310-cp310-win_amd64.whl”_, etc.

### In other words, our school can not install any torch higher than version 1.8.1.

In the non-fork so-vits-svc-4.0 program folder, there is a file called “requirements.txt”. We opened that file, and can see it says “torch==1.13.1”. Can we assume torch version 1.13.1 is the lowest minimum requirement for so-vits-svc program to run?

### Does it mean we can not install your amazing software on our school’s computers, because our Nvidia GPU are too old, and can’t reach your required pytorch 1.13.1 version? Or maybe it doesn’t matter, a lower pytorch 1.8.1 version can still run?

Too bad! My colleagues have already trained several G_43200.pth models on their home computers, and they can just simply copy these models to our school’s computers and start the voice inference right away. We don’t need to train on the classroom’s computers, we just need to infer on existing models, to demonstrate to our students. Inferring takes an awful lot less of GPU powers to do.

Has anyone tested this program on CUDA 10.1?

Please let me know. So, should I give up? Is it a death penalty for our students to see this?

![CUDA_10 1_User](https://user-images.githubusercontent.com/131915615/234706327-eba9799c-3c4b-4bd0-8854-f99d99471bb4.PNG)

**Comment by MaxMax2016** [comment]
I will test sovits5.0 for pytorch 1.8, maybe some parts have error, i think they can be fixed.

**Comment by MaxMax2016** [comment]
@TechVillain sovits5.0 can be used in torch1.8, my environment as below:


| NVIDIA-SMI 440.59       Driver Version: 440.59       CUDA Version: 10.2   |

Python 3.7.0 (default, Mar  3 2022, 17:36:18) 
[GCC 7.5.0] on linux


> Package                 Version
> ----------------------- ------------
> backports.lzma          0.0.14
> beautifulsoup4          4.10.0
> cycler                  0.11.0
> Cython                  3.0.0a10
> decorator               5.1.1
> ffmpeg-python           0.2.0
> filelock                3.6.0
> fsspec                  2023.1.0
> future                  0.18.3
> grpcio                  1.44.0
> huggingface-hub         0.12.0
> humanfriendly           10.0
> idna                    3.3
> importlib-metadata      4.11.2
> inflect                 5.4.0
> joblib                  1.1.0
> kaldiio                 2.17.2
> kiwisolver              1.3.2
> lazy_loader             0.2
> librosa                 0.10.0.post2
> llvmlite                0.38.0
> loguru                  0.6.0
> Markdown                3.3.6
> matplotlib              3.1.0
> msgpack                 1.0.5
> numba                   0.55.1
> numpy                   1.21.5
> oauthlib                3.2.0
> omegaconf               2.3.0
> packaging               21.3
> pip                     23.1.2
> pooch                   1.6.0
> protobuf                3.19.4
> pyasn1                  0.4.8
> pyasn1-modules          0.2.8
> pycparser               2.21
> pyparsing               3.0.7
> PySocks                 1.7.1
> python-dateutil         2.8.2
> pytorch-ranger          0.1.1
> pytorch-wavelets        1.3.0
> pytsmod                 0.3.3
> PyWavelets              1.3.0
> pyworld                 0.3.0
> PyYAML                  6.0
> regex                   2022.3.2
> requests                2.27.1
> requests-oauthlib       1.3.1
> resampy                 0.2.2
> rsa                     4.8
> scikit-learn            1.0.2
> scipy                   1.7.3
> sentencepiece           0.1.96
> setuptools              60.9.3
> six                     1.16.0
> soundfile               0.12.1
> soupsieve               2.3.1
> soxr                    0.3.5
> tensorboard             2.8.0
> tensorboard-data-server 0.6.1
> tensorboard-plugin-wit  1.8.1
> tensorboardX            2.5
> threadpoolctl           3.1.0
> tokenizers              0.12.1
> toml                    0.10.2
> torch                   1.8.0
> torch-complex           0.4.3
> torch-optimizer         0.3.0
> torchaudio              0.8.0
> torchvision             0.9.0
> tqdm                    4.63.0
> transformers            4.19.0
> typeguard               2.13.3
> typing_extensions       4.1.1
> urllib3                 1.26.8
> Werkzeug                2.0.3
> wheel                   0.37.1
> xmltodict               0.12.0
> yq                      2.14.0
> zipp                    3.7.0
>

**Comment by MaxMax2016** [comment]
And more:

> pip install torchcrepe
> pip install -U librosa

**Comment by TechVillain** [comment]
@MaxMax2016 Thank you 谢谢 Thank you!

So, you tested 10.2 on a Linux server and succeeded, can I assume if I run 10.1 on a local Windows computer, the results should be the same?

Also, after you install CUDA 10.2 Toolkit, did you have to install Microsoft Visual Composer with C or C++ pack in order to make CUDA work? Or MS VC is not needed?

Max, we already have a G_43200.pth model trained of 周杰伦's voice, but it was trained in so-vits-svc-4.0, on a different computer of CUDA 11.7 and pytorch 1.13.1 environment. Can this model be used in a CUDA 10 svc?

**Comment by TechVillain** [comment]
So, when a G_ model is trained, is it done and can be used in any svc, pytorch, torchaudio, and CUDA environment? Or it can only be used in the original environment in which it was originally trained?

MaxMax, I can send you this 周杰伦 G_ model via my Dropbox, if you are interested in testing it.

**Comment by MaxMax2016** [comment]
> @MaxMax2016 Thank you 谢谢 Thank you!
> 
> So, you tested 10.2 on a Linux server and succeeded, can I assume if I run 10.1 on a local Windows computer, the results should be the same?
> 
> Also, after you install CUDA 10.2 Toolkit, did you have to install Microsoft Visual Composer with C or C++ pack in order to make CUDA work? Or MS VC is not needed?
> 
> Max, we already have a G_43200.pth model trained of 周杰伦's voice, but it was trained in so-vits-svc-4.0, on a different computer of CUDA 11.7 and pytorch 1.13.1 environment. Can this model be used in a CUDA 10 svc?

I think it can be used in CUDA 10, vits is based on torch1.6. https://github.com/jaywalnut310/vits/blob/main/requirements.txt

**Comment by TechVillain** [comment]
So, you are saying G models can be used interchangably, trained in torch 1.13, then copied to another computer, and inferred in torch 1.8, with no problem?

乐队内部邮件：
“一个乐队的朋友已经用他的电脑培训好了一个周杰伦的G_模型，但是他是用CUDA 11.7和TORCH 1.13.1的环境培训的。请问如果我推理的环境跟他的不一样，比他的低，我的环境是CUDA 10.1和TORCH 1.8.1，那么我还能够使用他的那个G模型进行推理吗？”

**Comment by MaxMax2016** [comment]
i think so, also the infer can use only CPU without CUDA 10.1

**Comment by TechVillain** [comment]
Thx MaxMax!

This link：
https://github.com/svc-develop-team/so-vits-svc

When I download their svc-4.0 zip file and unzip it, the folder is only 190KB, very small! Is it normal? It supposed to be 4 to 5 GB? What's going on?

SVC的创始团队。我下载了页面上4.0的zip文件，解压缩后整个文件夹只有190KB大小。请问这正常吗？

该不会是他们把源代码给删了吧？不让别人再下载了？

**Comment by MaxMax2016** [comment]
Yes, it is normal. you can get info from README for download required models manually.

**Comment by TechVillain** [comment]
Awesome Max!

So which one is better, original svc-4.0, or voicepaw's GUI fork?

Do you know any good YouTube video, or Bilibili video, or detailed document, that I can refer to for setting up the environment, as a step by step guide?

**Comment by TechVillain** [comment]
Yo Max! Sup man! The pip list you sent me was just purely awesome! Please allow me a few days to go through it, and I will let you know the results.

If I can eventually successfully install svc-4.0 on a CUDA 10.1 Windows 7 machine, I'm gonna compose a rock song to celebrate! Seriously.

Once 4.0 is working, I'm gonna continue to install and test your 5.0, which is the newest svc version in the world.

Max, do you use stuff like Facebook, Instagram, Line, Bilibili, Twitter, Gmail, Whatsapp, etc? Can I add you as a friend, so I can send you my song?

Do you have your own songs? Send to me! I want to listen!

😄 🌹 🎸 🎹 💕

**Comment by MaxMax2016** [comment]
maxmax20160403@gmail.com
