### ISSUE TITLE
Another sample rate support?

### ISSUE THREAD

**Issue by futorio** [PlayVoice/so-vits-svc-5.0#50]
Hello! Is this repository support another train sample rate 44100?

**Comment by MaxMax2016** [comment]
don't support. it needs more GPU memory to train high sample rate. may be you can try so-vits-svc-fork.

**Comment by futorio** [comment]
I have 24g of vram on rtx 4090 card. It will not be enough?

**Comment by MaxMax2016** [comment]
my GPU is 10G. so I have not the abilities to develope high sample rate. you can try.

**Comment by futorio** [comment]
So for turn train to 44100 i need to change in preprocess_a.py script flag "-s 44100" and "sampling_rate" parameter in configs/base.yaml

**Comment by MaxMax2016** [comment]
nead to do more works, here use 10ms frame; for 44100, 10ms means 441 hop_size, this can not work; you may use https://github.com/svc-develop-team/so-vits-svc, this support large-v2 and bigvgan and 44100, or you can modify as this project.

**Comment by futorio** [comment]
Thank you for answers. Can i use pretrained models from bigvgan-large-v2 in so-vits-svc? I have noticed that there are differences in model file formats between the repositories.

**Comment by MaxMax2016** [comment]
pretrain model is 32k

**Comment by futorio** [comment]
Thanks for all answers!

**Comment by capric98** [comment]
Though issue is solved, still want to leave a comment IMHO 32k sample rate is more than enough for pure vocal data since human cannot produce 2k+ frequency voice. In this case 2*2k = 4k is enough theoretically.

**Comment by futorio** [comment]
> Though issue is solved, still want to leave a comment IMHO 32k sample rate is more than enough for pure vocal data since human cannot produce 2k+ frequency voice. In this case 2*2k = 4k is enough theoretically.

Yes i will try on 32k sample rate
