### ISSUE TITLE
处理train和Valid两个文本文件时，执行后，文本内无数据

### ISSUE THREAD

**Issue by ShadowLoveElysia** [PlayVoice/so-vits-svc-5.0#55]
如标题
LargeV2分支

**Comment by ShadowLoveElysia** [comment]
> 如标题
large V2

**Comment by sumaliqinghua** [comment]
仔细看日志，应该是中间某个步骤模块丢失了，我是python prepare/preprocess_ppg.py -w data_svc/waves-16k/ -p data_svc/whisper -t 1这一步有模块丢了
