### ISSUE TITLE
感觉推理过程中需要一个类似原版的slicer

### ISSUE THREAD

**Issue by KakaruHayate** [PlayVoice/so-vits-svc-5.0#6]
https://colab.research.google.com/drive/1PY1E4bDAeHbAD4r99D_oYXB46fG8nIA5?usp=sharing

如题，在colab中推理一首5min的歌曲也是会爆显存的（15g）

**Comment by MaxMax2016** [comment]
是的，这块在模型达到最优后，会逐步去完善

**Comment by MaxMax2016** [comment]
@KakaruHayate 您有没空弄呀？要不您有空弄了的话，提个PR?

**Comment by KakaruHayate** [comment]
> @KakaruHayate 您有没空弄呀？要不您有空弄了的话，提个PR?

够呛
