### ISSUE TITLE
F0 

### ISSUE THREAD

**Issue by Parisa-Bagherzadeh** [PlayVoice/so-vits-svc-5.0#64]
What's the f0 parameter?

**Comment by MaxMax2016** [comment]
pitch

**Comment by Parisa-Bagherzadeh** [comment]
> pitch

how to have high quality output ?
the input wav files have high quality but the output has poor quality

**Comment by MaxMax2016** [comment]
can you paste your input and output wave? or you can you use huggingface demo to compare.

**Comment by Parisa-Bagherzadeh** [comment]
> can you paste your input and output wave? or you can you use huggingface demo to compare.

the hugging face demo does not work
what's the problem?
