### ISSUE TITLE
Ask for training method about speaker embedding

### ISSUE THREAD

**Issue by 980202006** [PlayVoice/so-vits-svc-5.0#66]
Good Work!I want to train speaker embedding on my own data set, is there any relevant code or paper?

**Comment by MaxMax2016** [comment]
https://github.com/mozilla/TTS/tree/master/TTS/speaker_encoder

**Comment by 980202006** [comment]
Thank you!

**Comment by zdj97** [comment]
这个是说话人识别模型嘛  看他github里介绍的不多。换成其他声纹模型可行吗

**Comment by MaxMax2016** [comment]
> 这个是说话人识别模型嘛 看他github里介绍的不多。换成其他声纹模型可行吗

从头训练模型的话，换成其他声纹模型是可行的；微调SVC模型的话，换成其他声纹模型，收敛速度可能不是那么好。
