### ISSUE TITLE
BigVGAN and Bigger Sampling Rates

### ISSUE THREAD

**Issue by alefiury** [PlayVoice/so-vits-svc-5.0#71]
Congratulations on the repository! It's incredibly useful!

I have a question regarding the training of the BigVGAN model. It was originally trained at 22kHz and 24kHz, considering that in the so-vits pipeline, the vocoder is trained in conjunction with the acoustic model, is it possible to achieve satisfactory results by training at 44kHz, as done in the so-vits-fork repository, without having to pre-train the vocoder at 44khz? I noticed that this repository offers the option to train at 32kHz. In this case, was the checkpoint of the BigVGAN used also pre-trained at 32kHz?

**Comment by MaxMax2016** [comment]
this project use 32k only, bigvgan needs more GPU memory to train, i failed to train higher than 32k, the pretrain model is 32k.
