### ISSUE TITLE
双显卡提示no gpu find

### ISSUE THREAD

**Issue by hulululu7654321** [PlayVoice/so-vits-svc-5.0#77]
![image](https://github.com/PlayVoice/so-vits-svc-5.0/assets/116489967/d15588df-484b-46ac-9de0-94ead3ff086d)

![image](https://github.com/PlayVoice/so-vits-svc-5.0/assets/116489967/d943bc34-4ec6-490c-ad77-9a15f9de1372)

![image](https://github.com/PlayVoice/so-vits-svc-5.0/assets/116489967/34bb891b-7b92-4a96-8b08-5860cc48d471)

按主页的步骤一步一步下来，webui能打开了，但是点一键训练的时候提示找不到GPU，但是cuda又确实工作了一会

**Comment by zzpop** [comment]
我遇到过同样的问题，用pip卸载torch重装后解决了，可以试试看
