### ISSUE TITLE
请问一下推理时用到的spk参数

### ISSUE THREAD

**Issue by EstelleSchwarzer** [PlayVoice/so-vits-svc-5.0#8]
configs/singers下的应该是debug模型的预设吧，用自己训练的模型的时候这个参数应该选哪个npy呢

**Comment by MaxMax2016** [comment]
用所用的npy求个均值

**Comment by EstelleSchwarzer** [comment]
那这边是直接使用speaker生成的npy吗

**Comment by MaxMax2016** [comment]
恩 python prepare/preprocess_speaker.py data_svc/waves-16k/ data_svc/speaker

**Comment by EstelleSchwarzer** [comment]
使用同一说话人的不同素材的音色npy差别会很大吗，是否使用特定语气生成的npy会好一点

**Comment by MaxMax2016** [comment]
> 使用同一说话人的不同素材的音色npy差别会很大吗，是否使用特定语气生成的npy会好一点

确实不同素材存在音色差异特别大的情况，所以训练的时候使用的是每个音频对应的音色，推理使用特定语气生成的npy会好一点
