### ISSUE TITLE
生成pitch的csv那一步报错

### ISSUE THREAD

**Issue by zxwwxz001** [PlayVoice/so-vits-svc-5.0#86]
训练完毕后生成pitch的csv时报错，内容如下
/notebooks/so-vits-svc-5.0# python pitch/inference.py -w test.wav -p test.csv
test.wav
test.csv
Traceback (most recent call last):
  File "/notebooks/so-vits-svc-5.0/pitch/inference.py", line 93, in <module>
    pitch = compute_f0_sing(args.wav, device)
  File "/notebooks/so-vits-svc-5.0/pitch/inference.py", line 46, in compute_f0_sing
    pitch = crepe.predict(
  File "/notebooks/so-vits-svc-5.0/crepe/core.py", line 120, in predict
    probabilities = infer(frames, model)
  File "/notebooks/so-vits-svc-5.0/crepe/core.py", line 558, in infer
    crepe.load.model(frames.device, model)
  File "/notebooks/so-vits-svc-5.0/crepe/load.py", line 30, in model
    torch.load(file, map_location=device))
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.

在安装环境那一节的测试代码也报同样的错
使用的是paperspace的主机，依赖包按照requirements.txt安装完毕
具体版本如下
Python 3.9.16
pip 23.1.2
pip list
Package                           Version
--------------------------------- --------------------
absl-py                           1.4.0
agate                             1.6.0
agate-dbf                         0.2.0
agate-excel                       0.2.3
agate-sql                         0.5.2
aiofiles                          23.1.0
aiohttp                           3.8.3
aiosignal                         1.3.1
altair                            5.0.1
antlr4-python3-runtime            4.9.3
anyio                             3.6.2
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
asttokens                         2.2.1
astunparse                        1.6.3
async-timeout                     4.0.2
attrs                             18.2.0
audioread                         3.0.0
awscli                            1.25.91
Babel                             2.11.0
backcall                          0.2.0
beautifulsoup4                    4.11.1
bleach                            6.0.0
blis                              0.7.9
boto3                             1.24.90
botocore                          1.27.90
cached-property                   1.5.2
cachetools                        5.3.0
catalogue                         2.0.8
certifi                           2019.11.28
cffi                              1.15.1
chardet                           3.0.4
charset-normalizer                2.1.1
chex                              0.1.5
click                             8.1.3
click-completion                  0.5.2
click-didyoumean                  0.3.0
click-help-colors                 0.9.1
cloudpickle                       2.2.0
colorama                          0.4.3
comm                              0.1.2
confection                        0.0.4
contourpy                         1.0.7
csvkit                            1.0.2
cycler                            0.11.0
cymem                             2.0.7
Cython                            0.29.32
datasets                          2.4.0
dbfread                           2.0.7
dbus-python                       1.2.16
debugpy                           1.6.6
decorator                         5.1.1
defusedxml                        0.7.1
dill                              0.3.5.1
dm-tree                           0.1.8
docker-pycreds                    0.4.0
docutils                          0.16
entrypoints                       0.4
et-xmlfile                        1.0.1
etils                             1.0.0
exceptiongroup                    1.1.0
executing                         1.2.0
fastapi                           0.100.0
fastjsonschema                    2.16.2
ffmpy                             0.3.0
filelock                          3.9.0
flatbuffers                       1.12
flax                              0.6.3
fonttools                         4.38.0
frozenlist                        1.3.3
fsspec                            2023.1.0
future                            0.18.2
gast                              0.4.0
gdown                             4.5.1
gitdb                             4.0.10
GitPython                         3.1.30
google-auth                       2.16.0
google-auth-oauthlib              0.4.6
google-pasta                      0.2.0
gql                               3.0.0a6
gradient                          2.0.6
gradient-utils                    0.5.0
gradio                            3.36.1
gradio_client                     0.2.9
graphql-core                      3.1.7
greenlet                          2.0.1
grpcio                            1.51.1
h11                               0.14.0
h5py                              3.8.0
halo                              0.0.31
httpcore                          0.17.3
httpx                             0.24.1
huggingface-hub                   0.16.4
idna                              2.8
imageio                           2.25.0
importlib-metadata                6.0.0
importlib-resources               5.10.2
iniconfig                         2.0.0
ipykernel                         6.16.0
ipython                           8.5.0
ipython-genutils                  0.2.0
ipywidgets                        8.0.2
isodate                           0.6.0
jax                               0.4.1
jaxlib                            0.4.1+cuda11.cudnn82
jdcal                             1.0
jedi                              0.18.2
Jinja2                            3.1.2
jmespath                          1.0.1
joblib                            1.2.0
json5                             0.9.11
jsonify                           0.5
jsonschema                        4.17.3
jupyter-client                    7.3.4
jupyter-contrib-core              0.4.2
jupyter-contrib-nbextensions      0.7.0
jupyter_core                      5.1.5
jupyter-highlight-selected-word   0.2.0
jupyter-nbextensions-configurator 0.6.1
jupyter-server                    1.23.5
jupyter-server-mathjax            0.2.6
jupyterlab                        3.4.6
jupyterlab-git                    0.41.0
jupyterlab-pygments               0.2.2
jupyterlab_server                 2.19.0
jupyterlab-snippets               0.4.1
jupyterlab-widgets                3.0.5
keras                             2.9.0
Keras-Preprocessing               1.1.2
kiwisolver                        1.4.4
langcodes                         3.3.0
leather                           0.3.3
libclang                          15.0.6.1
librosa                           0.9.1
linkify-it-py                     1.0.3
llvmlite                          0.40.1
log-symbols                       0.0.14
lxml                              4.5.0
Markdown                          3.4.1
markdown-it-py                    2.1.0
MarkupSafe                        2.1.2
marshmallow                       2.21.0
matplotlib                        3.6.1
matplotlib-inline                 0.1.6
mdit-py-plugins                   0.3.3
mdurl                             0.1.2
mistune                           2.0.4
msgpack                           1.0.4
multidict                         6.0.4
multiprocess                      0.70.13
murmurhash                        1.0.9
nbclassic                         0.4.8
nbclient                          0.7.2
nbconvert                         7.2.9
nbdime                            3.1.1
nbformat                          5.7.3
nest-asyncio                      1.5.6
networkx                          3.0
nltk                              3.7
notebook                          6.5.2
notebook_shim                     0.2.2
numba                             0.57.1
numpy                             1.23.4
oauthlib                          3.2.2
omegaconf                         2.3.0
opencv-python                     4.6.0.66
openpyxl                          3.0.3
opt-einsum                        3.3.0
optax                             0.1.4
orbax                             0.1.0
orjson                            3.9.2
packaging                         23.0
pandas                            1.5.0
pandocfilters                     1.5.0
parsedatetime                     2.4
parso                             0.8.3
pathtools                         0.1.2
pathy                             0.10.1
pexpect                           4.8.0
pickleshare                       0.7.5
Pillow                            9.2.0
pip                               23.1.2
platformdirs                      2.6.2
pluggy                            1.0.0
pooch                             1.7.0
preshed                           3.0.8
progressbar2                      4.2.0
prometheus-client                 0.9.0
promise                           2.3
prompt-toolkit                    3.0.36
protobuf                          3.19.6
psutil                            5.9.4
ptyprocess                        0.7.0
pure-eval                         0.2.2
pyarrow                           10.0.1
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pycparser                         2.21
pydantic                          1.9.2
pydub                             0.25.1
Pygments                          2.14.0
PyGObject                         3.36.0
pymongo                           3.13.0
pyparsing                         3.0.9
pyrsistent                        0.19.3
PySocks                           1.7.1
pytest                            7.2.1
python-apt                        2.0.1
python-dateutil                   2.8.2
python-distutils-extra            2.39
python-multipart                  0.0.6
python-slugify                    4.0.0
python-utils                      3.4.5
pytimeparse                       1.1.5
pytz                              2022.7.1
PyWavelets                        1.4.1
pyworld                           0.3.3
PyYAML                            5.4.1
pyzmq                             25.0.0
regex                             2022.10.31
requests                          2.28.2
requests-oauthlib                 1.3.1
requests-toolbelt                 0.10.1
requests-unixsocket               0.2.0
resampy                           0.4.2
responses                         0.18.0
rich                              13.2.0
rsa                               4.7.2
s3transfer                        0.6.0
scikit-image                      0.19.3
scikit-learn                      1.1.2
scipy                             1.9.2
seaborn                           0.12.0
semantic-version                  2.10.0
Send2Trash                        1.8.0
sentence-transformers             2.2.2
sentencepiece                     0.1.97
sentry-sdk                        1.14.0
setproctitle                      1.3.2
setuptools                        66.1.1
shellingham                       1.5.0.post1
shortuuid                         1.0.11
six                               1.14.0
smart-open                        6.3.0
smmap                             5.0.0
sniffio                           1.3.0
soundfile                         0.12.1
soupsieve                         2.3.2.post1
spacy                             3.4.1
spacy-legacy                      3.0.12
spacy-loggers                     1.0.4
spinners                          0.0.24
SQLAlchemy                        1.4.41
srsly                             2.4.5
stack-data                        0.6.2
starlette                         0.27.0
tabulate                          0.9.0
tensorboard                       2.9.1
tensorboard-data-server           0.6.1
tensorboard-plugin-wit            1.8.1
tensorflow                        2.9.2
tensorflow-estimator              2.9.0
tensorflow-io-gcs-filesystem      0.30.0
tensorstore                       0.1.30
termcolor                         2.2.0
terminado                         0.17.1
terminaltables                    3.1.10
thinc                             8.1.7
threadpoolctl                     3.1.0
tifffile                          2023.1.23.1
tinycss2                          1.2.1
tokenizers                        0.12.1
tomli                             2.0.1
toolz                             0.12.0
torch                             1.12.1+cu116
torchaudio                        0.12.1+cu116
torchcrepe                        0.0.20
torchvision                       0.13.1+cu116
tornado                           6.1
tqdm                              4.64.1
traitlets                         5.8.1
transformers                      4.21.3
typer                             0.4.2
typing_extensions                 4.7.1
uc-micro-py                       1.0.2
Unidecode                         1.1.1
urllib3                           1.26.14
uvicorn                           0.22.0
wandb                             0.13.4
wasabi                            0.10.1
wcwidth                           0.2.6
webencodings                      0.5.1
websocket-client                  0.57.0
websockets                        11.0.3
Werkzeug                          2.2.2
wheel                             0.35.1
widgetsnbextension                4.0.5
wrapt                             1.14.1
xgboost                           1.6.2
xlrd                              1.1.0
xxhash                            3.2.0
yarl                              1.8.2
zipp                              3.11.0

**Comment by MaxMax2016** [comment]
Download pitch extractor [crepe full](https://github.com/maxrmorrison/torchcrepe/tree/master/torchcrepe/assets)，put full.pth into crepe/assets. 检查一下full文件大小对不对 84.9 MB

**Comment by zxwwxz001** [comment]
是这个原因，搞定了，谢谢
