### ISSUE TITLE
Suggestion and question.

### ISSUE THREAD

**Issue by Turokirill** [PlayVoice/so-vits-svc-5.0#89]
Hello, you can add the function of running 1 file in different "pitch". For example, I process 1 file and get 4 audio files with different "pitch" output. And so that you can choose the "pitch" range from -5 to -2, for example (the same 4 files). To quickly understand which "pitch" is more suitable. And also the question, what is the best learning rate to set?
p.s And do I need to choose a language for the whisper model somewhere? Or does he define it himself?

**Comment by MaxMax2016** [comment]
whisper large is multilingual model, whisper audio encoder using in this project can be treated as language indepnedent.

what is the best learning rate to set? There is no best setting for  learning rate.

To quickly understand which "pitch" is more suitable.  I can try it.
