### ISSUE TITLE
似乎训练到一定的量就会自动停下来，如何让他继续。

### ISSUE THREAD

**Issue by Yuxiza** [PlayVoice/so-vits-svc-5.0#9]
找了一下config 没看见哪个量控制这个。可能是我看漏了qwq

**Comment by MaxMax2016** [comment]
是这个的原因吧，https://github.com/PlayVoice/so-vits-svc-5.0/blob/main/vits_extend/train.py#L111
遗漏了，应该使用config里面的设置的epochs: 10000

**Comment by Yuxiza** [comment]
ok了，谢谢(｀・ω・´)

> 是这个的原因吧，https://github.com/PlayVoice/so-vits-svc-5.0/blob/main/vits_extend/train.py#L111 遗漏了，应该使用config里面的设置的epochs: 10000
