### ISSUE TITLE
NCCL error with multi gpu on windows

### ISSUE THREAD

**Issue by crankyz** [PlayVoice/so-vits-svc-5.0#97]
raise RuntimeError("Distributed package doesn't have NCCL " "built in")
founded solving dosent help ( os.environ["PL_TORCH_DISTRIBUTED_BACKEND"] = "gloo"
with one gpu works ok.

**Comment by MaxMax2016** [comment]
https://discuss.pytorch.org/t/runtimeerror-distributed-package-doesnt-have-nccl-built-in/176744/13

**Comment by crankyz** [comment]
everything work fine if in base.yaml change nccl to gloo.
